name: Electricity Carbon Data

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: ELEC_API_KEY  # Refer to the environment secret

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          api_token: ${{ secrets.ELEC_API_KEY }}  # Use the environment-specific secret
        run: |
          set -e
          python rest_api_pipeline.py
